What is the return value of reject in the following code? Why?

[1, 2, 3].reject do |num|
  puts num
end

So lets look at the ruby docs...

Returns a new Array whose elements are all those from self for which the block returns false or nil

Based on this it seems that this does the opposite of count in terms of evaluating for false(or nil) rather than true. Also it returns an array itself. A NEW ARRAY.

Example:

a = [:foo, 'bar', 2, 'bat']
a1 = a.reject {|element| element.to_s.start_with?('b') }
a1 # => [:foo, 2]

Returns a new enumerator if no block is given

Example:

a = [:foo, 'bar', 2]
a.reject # => #<Enumerator: [:foo, "bar", 2]:reject>
